variables:
- name: message
  value: 'Hello world'

stages:
  - stage: first_stage
    pool: sspool
    jobs:
    - job: first_job
      steps: 
        - script: echo $(message)
    - job: second_job
      steps: 
        - script: echo $(message)

  - stage: second_stage
    pool: sspool
    jobs:
    - job: third_job
      steps: 
        - script: echo $(message)
    - job: fourth_job
      steps: 
        - script: echo $(message)
