variables:
  - message: 'Hello world'

stages:
  - stage: first-stage
    jobs:
    - job: first-job
      steps: 
        - script: echo $(message)
    - job: second-job
      steps: 
        - script: echo $(message)

  - stage: second-stage
    jobs:
    - job: third-job
      steps: 
        - script: echo $(message)
    - job: fourth-job
      steps: 
        - script: echo $(message)
